services:
  backend:
    build: ./backend
    ports:
      - 6969:6969
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=http://localhost:5173

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_BASE_URL=http://localhost:6969
    depends_on:
      - backend
